export const APPOINTMENTS_LIST = "APPOINTMENTS_LIST";
export const APPOINTMENTS_DATA = "APPOINTMENTS_DATA";
export const APPOINTMENTS_LIST_COMPLETED = "APPOINTMENTS_LIST_COMPLETED";
export const APPOINTMENTS_LIST_PENDING = "APPOINTMENTS_LIST_PENDING";